#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely

invic(){
	echo "I am invincible!!!"
}
trap invic SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
